OBJECTS = [
    {
        "name": "Sodium",
        "rarity": 1,
        "color": 8829246,
        "image": "https://i.imgur.com/wvyymCl.png",
        "card": "https://i.imgur.com/yIZCVIb.png",
    },
    {
        "name": "OsciDexy",
        "rarity": 0.5,
        "color": 000000,
        "image": "https://i.imgur.com/0Whonui.png",
        "card": "https://i.imgur.com/kVIDH5a.png",
    },
    {
        "name": "Kertas amplas hitam",
        "rarity": 43.0,
        "color": 5329246,
        "image": "https://imgur.com/iHrwB9B.png",
    },
    {
        "name": "Breadnote",
        "rarity": 30,
        "color": 9498256,
        "image": "https://imgur.com/ql5J6bR.png",
    },
    {
        "name": "Orygamy",
        "rarity": 22.2,
        "color": 16738740,
        "image": "https://imgur.com/gcHHGsI.png",
    },
    {
        "name": "Progressbar 95",
        "rarity": 24,
        "color": 16738740,
        "image": "https://imgur.com/oRapg32.png",
    },
    {
        "name": "Kelapa Sawit",
        "rarity": 33.3,
        "color": 5745531,
        "image": "https://imgur.com/w1vcNBQ.png",
    },
    {
        "name": "Canti",
        "rarity": 43.8,
        "color": 15414351,
        "image": "https://i.imgur.com/RTvDPXd.png",
    },
    {
        "name": "Testy",
        "rarity": 24.9,
        "color": 6746660,
        "image": "https://i.imgur.com/qRft5l0.png",
        "card": "https://i.imgur.com/ZU4FKm4.png"
    },
    {
        "name": "Flora",
        "rarity": 38.8,
        "color": 9759720,
        "image": "https://i.imgur.com/YthmK7A.png",
    },
    {
        "name": "Author",
        "rarity": 49.8,
        "color": 15414351,
        "image": "https://imgur.com/VzpQyC8.png",
    },
    {
        "name": "Branket",
        "rarity": 18.8,
        "color": 15414351,
        "image": "https://i.imgur.com/G44H1ET.png",
    },
    {
        "name": "Baygon",
        "rarity": 19,
        "color": 4977181,
        "image": "https://imgur.com/fU9lCC5.png",
    },
    {
        "name": "Indoflag",
        "rarity": 18.8,
        "color": 15414351,
        "image": "https://i.imgur.com/kJWsNbV.png",
    },
    {
        "name": "Bluket",
        "rarity": 21.1,
        "color": 15414351,
        "image": "https://i.imgur.com/lu0HfMQ.png",
    },
    {
        "name": "Relocky",
        "rarity": 30,
        "color": 15414351,
        "image": "https://i.imgur.com/FbZmrSx.png",
    },
    {
        "name": "Love Bottle",
        "rarity": 44.3,
        "color": 15414351,
        "image": "https://i.imgur.com/0hKnNE4.png",
    },
    {
        "name": "Music Note",
        "rarity": 18.8,
        "color": 15414351,
        "image": "https://i.imgur.com/3TcYY9j.png",
    },
    {
        "name": "Magic Orb Wand",
        "rarity": 19.9,
        "color": 15414351,
        "image": "https://i.imgur.com/AnfiUDM.png",
    },
    {
        "name": "Obsidian",
        "rarity": 18.8,
        "color": 15414351,
        "image": "https://i.imgur.com/XFA14cA.png",
    },
    {
        "name": "Rastra Bluket",
        "rarity": 40.8,
        "color": 15414351,
        "image": "https://i.imgur.com/6YD1WdT.png",
    },
    {
        "name": "Rastra",
        "rarity": 29,
        "color": 15414351,
        "image": "https://i.imgur.com/EWwyv9E.png",
    },
    {
        "name": "Soekarno",
        "rarity": 28.8,
        "color": 15414351,
        "image": "https://i.imgur.com/D0EmJeg.png",
    },
    {
        "name": "Indonesian Flag",
        "rarity": 51.8,
        "color": 15414351,
        "image": "https://i.imgur.com/UjDZqhh.png",
        "card": "https://i.imgur.com/qBdvNNN.png"
    },
    {
        "name": "Stik",
        "rarity": 40.8,
        "color": 15414351,
        "image": "https://i.imgur.com/ZBJXQwT.png",
    },
    {
        "name": "Photo Inserter",
        "rarity": 50.8,
        "color": 15414351,
        "image": "https://i.imgur.com/aSN8ChK.png",
    },
    {
        "name": "KTP",
        "rarity": 40.8,
        "color": 15414351,
        "image": "https://i.imgur.com/iuPveaq.png",
    },
    {
        "name": "Lija",
        "rarity": 5.5555,
        "color": 15414351,
        "image": "https://i.imgur.com/e758c3Z.png",
    },
    {
        "name": "Kopi Lawak",
        "rarity": 15.7,
        "color": 15414351,
        "image": "https://i.imgur.com/N1FrTq8.png",
    },
    {
        "name": "Pisgor",
        "rarity": 28,
        "color": 15414351,
        "image": "https://i.imgur.com/DgI74iU.png",
    },
    {
        "name": "Lup",
        "rarity": 30,
        "color": 15414351,
        "image": "https://i.imgur.com/Payatd5.png",
    },
    {
        "name": "Planter",
        "rarity": 27,
        "color": 15414351,
        "image": "https://i.imgur.com/JrRoKi2.png",
    },
    {
        "name": "Rafles",
        "rarity": 30,
        "color": 15414351,
        "image": "https://i.imgur.com/Tq09eI8.png",
    },
    {
        "name": "sop di bius🥶",
        "rarity": 50,
        "color": 1,
        "image": "https://i.imgur.com/kgOj6Yi.gif",
    },
]
